config/routes.rb
Rails.application.routes.draw do
  get 'references/new',  to: 'references#new'

  post 'references/new'
  
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :references
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :authenticate_user!

 def index
    @references = Reference.all
  end


  def new
    @reference = Reference.new
  end
 
  def show
    @reference = Reference.find(params[:id])
  end

  def edit
    @reference = Reference.find(params[:id])
  end

  def update
    @reference = Reference.find(params[:id])
    if @reference.update(reference_params)
      redirect_to @reference 
    else
      render 'edit'
    end
  end

  def create
      @reference = Reference.new(reference_params)
      if @reference.save
        redirect_to @reference, notice: "Successfully added reference!"
      else
        render 'new'
      end
    end

   def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy

    redirect_to references_path
  end
  
    private

      def reference_params
        params.require(:reference).permit(:number, :title, :kind,
                                     :author, :pubdate, :userid, :notes)


      end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>

 <li><%= link_to 'Add Reference', references_new_path %></li>
 <li><%= link_to 'Display References', references_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web app is created for COMP204P Scenario Week 3. <br>
The team members are Nancy Amelia, Jason In, Zi Jian Sim, Vania Desmonda Gunawan Setiono, and Pauline Conde.
</p>

app/views/references/edit.html.erb
<% provide(:title, 'Sign up') %>
<h1 align="center">Edit a Reference</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for @reference do |f| %>
    <%= render 'shared/error_messages' %>


      <%= f.number_field :number, label: "Reference number", class: 'form-control', :required => true %>

<br>

      <%= f.select :kind, ["Book", "Research paper/Journal article", "Web page", "Sound recording", "Film/TV recording"],
      {label: "Where did you get this reference from?"} %>


<br>

      <%= f.text_field :title, label: "Article title", class: 'form-control', :required => true  %>


<br>

      <%= f.text_field :author, class: 'form-control' %>

<br>

      <%= f.date_select :pubdate, :prompt => {:year => "Year", :month => "Month"},
      :start_year => 1800, :end_year => 2016, :discard_day => true, :label => "Publication Date" %>

<br>

      <%= f.text_field :userid, label: "User ID",class: 'form-control' %>

<br>

      <%= f.text_field :notes, label: "Notes",class: 'form-control' %>

<br>

      <%= f.submit "Confirm changes", class: "btn btn-primary" %>
        <%= button_to 'Back', references_path,:class =>"btn btn-outline-primary",:method => :get %>
    <% end %>
  </div>

</div>

app/views/references/index.html.erb
<style>
.tableheaders th
{
  font-size: 18px;
}
</style>

<div class="container">
  <div class="row">
    <h1 align="center">References</h1>
    <div class="table-responsive">
      <table class="table table-hover" id ="RefTable">
        <tbody>
          <tr class="tableheaders">
            <th> User Id </th>
            <th> Number</th>
            <th> Kind </th>
            <th> Title </th>
            <th> Author </th>
            <th> PubDate </th>
            <th> Notes </th>
            <th colspan= "3"> Manage </th>
          </tr>

          <% @references.each do |reference| %>
          <tr>
          <td><%= reference.userid %></td>
          <td><%= reference.number %></td>
          <td><%= reference.kind %></td>
          <td><%= reference.title %></td>
          <td><%= reference.author %></td>
          <td><%= reference.pubdate %></td>
          <td><%= reference.notes %></td>
          <td ><%= button_to 'Show', reference_path(reference) ,:class =>"btn btn-outline-primary",:method => :get %></td>
          <td><%= button_to 'Edit', edit_reference_path(reference),:class =>"btn btn-outline-warning",:method => :get %></td>
          <td><%= button_to 'Delete', reference_path(reference),:class =>"btn btn-outline-danger", method: :delete, data:{confirm: 'Are you sure?'}%></td>

        </tr>

          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/references/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 align="center">Add a Reference</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for @reference do |f| %>
    <%= render 'shared/error_messages' %>


      <%= f.number_field :number, label: "Reference number", class: 'form-control', :required => true %>

<br>

      <%= f.select :kind, ["Book", "Research paper/Journal article", "Web page", "Sound recording", "Film/TV recording"],
      {label: "Where did you get this reference from?"} %>


<br>

      <%= f.text_field :title, label: "Article title", class: 'form-control', :required => true  %>


<br>

      <%= f.text_field :author, class: 'form-control' %>

<br>

      <%= f.date_select :pubdate, :prompt => {:year => "Year", :month => "Month"},
      :start_year => 1800, :end_year => 2016, :discard_day => true, :label => "Publication Date" %>

<br>

      <%= f.text_field :userid, label: "User ID",class: 'form-control' %>

<br>

      <%= f.text_field :notes, label: "Notes",class: 'form-control' ,:required => true %>

<br>

      <%= f.submit "Add Reference", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= button_to 'Back', references_path,:class =>"btn btn-outline-primary",:method => :get %>

app/views/references/show.html.erb
<div class =container>
<h3>Reference</h3>

<p>ID: <%= @reference.id if @reference.id %></p>
<p>Number: <%= @reference.number if @reference.number %></p>
<p>Kind: <%= @reference.kind if @reference.kind %></p>
<p>Title: <%= @reference.title if @reference.title %></p>
<p>Author: <%= @reference.author if @reference.author %></p>
<p>Date: <%= @reference.pubdate if @reference.pubdate %></p>
<p>UserID: <%= @reference.userid if @reference.userid %></p>
<p>Notes: <%= @reference.notes if @reference.notes %></p>
<%= button_to 'Edit', edit_reference_path(@reference),:class =>"btn btn-outline-primary",:method => :get,:style =>"float:left" %>

<%= button_to 'Back', references_path,:class =>"btn btn-outline-primary",:method => :get %>
</div>

app/views/shared/_error_messages.html.erb
<% if @reference.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@reference.errors.count, "error") %>.
    </div>
    <ul>
    <% @reference.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>